### ISSUE TITLE
Define the application's models

### ISSUE THREAD

**Issue by mateusnr** [Desenho-2018-2/Order#1]

**Comment by Bumbleblo** [comment]
Hey, Mateus. Give me some details of the problem. Do you have some idea how to elaborate this models ?

**Comment by Bumbleblo** [comment]
In this service the models layer has some tables to control the orders of service. You should pay attention to all orders of a session arriving on the table at the same time.

Having this in mind, I think in tree tables, Command (show all session and the total cost of the service), Session (I don't like this lexicon, but, the session simply represent a group of orders - think of you and a group of friends going to a restaurant, would not you like everyone's food to arrive at the same time? ) and the Order (this is the smaller "layer", represent an order into the tasker service).
![2018-11-15-212009_552x309_scrot](https://user-images.githubusercontent.com/13987085/48588277-9650c800-e91d-11e8-9abe-ba034acb61cd.png)

**Comment by mateusnr** [comment]
Command should be renamed to OrderPad

**Comment by cjjcastro** [comment]
What is the difference between Command and Section? Could not you just create a class to do this job?

**Comment by mateusnr** [comment]
Guess I'm probably deprecating the Session class and I'm putting the remaining fields into the OrderPad, because if you think about it, it kinda doesn't make sense to keep it in the project.

**Comment by Bumbleblo** [comment]
The session is required to handle the case of request of orders come in sets.

Example: A group of friends request a entrance and after this request a dinner

**Comment by mateusnr** [comment]
Session will be kept to track an order containing more than one product

**Comment by mateusnr** [comment]
We are going to work under the defined modeling while no suggestions show up
